# Generated by Django 4.2.23 on 2025-07-16 01:52

from typing import List, Tuple

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: List[Tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Title", max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("inventory", models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("collection", models.CharField(blank=True, null=True)),
                ("category", models.CharField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
