name: Checks

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  linter:
    name: Code Formatting
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HUSTLR_APP_USER }}
          password: ${{ secrets.HUSTLR_APP_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
